services:
  —Åhecklist-backend:
    build: .
    ports:
      - "8011:8001"
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh -c "chmod +x ./docker/app.sh && ./docker/app.sh"
    depends_on:
      - db
    networks:
      - photo_registry_photo_registry


  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - photo_registry_photo_registry


volumes:
  db_data:

networks:
  photo_registry_photo_registry:
    external: true
