# Generated by Django 5.1.3 on 2024-11-20 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='element',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='order',
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('OK', 'Ok'), ('NOT_OK', 'Not OK')], default='OK')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.element')),
            ],
        ),
        migrations.DeleteModel(
            name='ChecklistElement',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
    ]
