# Generated by Django 5.1.3 on 2024-11-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_element_remove_checklist_element_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
