# Generated by Django 5.1.3 on 2024-12-04 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_alter_element_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ENGINE', 'ДВС'), ('LIGHTING', 'Свет'), ('SUSPENSION', 'Подвеска'), ('BRAKES', 'Тормоза')])),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='state',
            field=models.CharField(choices=[('OK', 'Исправно'), ('NOT_OK', 'Несправно, некритическое состояние'), ('CRITICAL', 'Неисправно, критическое состояние'), ('ABSENCE', 'Отсутствует')], default='OK', verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='element',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='checklists.category'),
        ),
    ]
