# Generated by Django 5.1.3 on 2024-12-05 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_category_element_description_alter_check_state_and_more'),
        ('orders', '0002_alter_order_car_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('ENGINE', 'ДВС'), ('LIGHTING', 'Свет'), ('SUSPENSION', 'Подвеска'), ('BRAKES', 'Тормоза'), ('EXHAUST', 'Выхлоп')]),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.car')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.element')),
            ],
        ),
    ]
