# Generated by Django 5.1.3 on 2024-12-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_category_element_description_alter_check_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('ENGINE', 'ДВС'), ('LIGHTING', 'Свет'), ('SUSPENSION', 'Подвеска'), ('BRAKES', 'Тормоза'), ('EXHAUST', 'Выхлоп')]),
        ),
    ]
