# Generated by Django 5.1.3 on 2024-12-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_alter_category_options_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
