# Generated by Django 5.1.3 on 2024-12-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_check_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='check',
            name='state',
            field=models.CharField(choices=[('OK', 'Исправно'), ('NOT_OK', 'Несправно')], default='OK', verbose_name='Состояние'),
        ),
    ]
