# Generated by Django 5.1.3 on 2024-12-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_alter_category_options_alter_category_title'),
        ('checklists', '0007_alter_check_photo_alter_check_state'),
    ]

    operations = [
    ]
