# Generated by Django 5.1.3 on 2025-04-29 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0008_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='state',
            field=models.CharField(choices=[('OK', 'Исправно'), ('NOT_OK', 'Несправно'), ('NOT_EQUIPPED', 'Не оснащено')], default='OK', verbose_name='Состояние'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AddField(
            model_name='element',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='checklists.subcategory'),
        ),
    ]
