# Generated by Django 5.1.3 on 2025-09-03 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_alter_check_state_subcategory_element_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='checklists.category'),
        ),
    ]
