# Generated by Django 5.1.3 on 2025-04-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0008_merge_20241212_1349'),
        ('checklists', '0009_alter_check_state_subcategory_element_sub_category'),
    ]

    operations = [
    ]
