# Generated by Django 5.1.3 on 2025-09-08 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_check_comment_alter_subcategory_category'),
        ('orders', '0002_alter_order_car_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='checklists.element'),
        ),
        migrations.AlterField(
            model_name='check',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='orders.order'),
        ),
    ]
