# Generated by Django 5.1.3 on 2025-09-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_merge_20250430_1507'),
        ('checklists', '0011_alter_check_element_alter_check_order'),
    ]

    operations = [
    ]
