# Generated by Django 5.1.3 on 2025-09-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0012_merge_20250912_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
